SELECT HIREDATE
FROM EMP
WHERE HIREDATE = '80/12/17';

ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';

SELECT HIREDATE
FROM EMP;

-- BETWEEN
SELECT *
FROM EMP
--WHERE SAL >= 1500 AND SAL <=2000;
WHERE SAL BETWEEN 1500 AND 2000;  -- caution> 이상 이하 임... 

SELECT *
FROM EMP
WHERE ENMAE LIKE '%N';      -- ending with N
WHERE ENAME LIKE 'A%N';     -- starting with A, ending with N
WHERE ENAME LIKE '%N%';     -- including N
WHERE ENAME REGEXP_LIKE      -- regular expression

SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

SELECT *
FROM EMP
WHERE COMM IS NULL;

-- 사원들중에 보너스가 500보다 작은 사람
SELECT *
FROM EMP
WHERE COMM < 500;

SELECT NVL(NULL, 0), NVL(100, 0)     -- 
FROM DUAL;

SELECT *
FROM EMP
WHERE NVL(COMM,0) < 500;

SELECT *
FROM EMP
WHERE SAL > 1000
ORDER BY SAL ASC;

SELECT *
FROM EMP
WHERE SAL > 1000
ORDER BY SAL DESC;  --descend

DESC EMP;  --describe

----------------------------------------------------------------------

SELECT POWER(2,64)
FROM DUAL;

SELECT MOD(121, 10), CEIL(123.45), FLOOR(123.45), TRUNC(121.345, 2)
FROM DUAL

ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD HH24:MI:SS';
SELECT SYSDATE -- present day
FROM DUAL;

SELECT DECODE('LOVE', 'LOV', 'TRUE', 'FALSE')
FROM DUAL;

SELECT DEPTNO, NAME, 
       DECODE(DEPTNO, 101, 'COMPUTER ENGINEERING', 'ETC')
FROM PROFESSOR;

SELECT DEPTNO, NAME, 
       DECODE(DEPTNO, 101, 'COMPUTER ENGINEERING', 102, 'MULTIMEDIA ENGINEERING', 103, 'SOFTWARE ENGINEERING', 'ETC') "DNAME"
FROM PROFESSOR;

SELECT DEPTNO, NAME, 
       DECODE(DEPTNO, 101, DECODE(NAME, '조인형', 'BEST!'))
FROM PROFESSOR;

--------------------------------------------------------------------

-- 3교시

SELECT DEPTNO, NAME, 
       DECODE(DEPTNO, 101, DECODE(NAME, '조인형', 'BEST', 'GOOD')) "ETC"
FROM PROFESSOR;

SELECT DEPTNO, NAME,
       DECODE(DEPTNO, 101, 'COMPUTER', ' ')
FROM PROFESSOR;       

-- ORDER BY COMM DESC, SAL DESC 처럼 여러 열을 정렬할 수 

SELECT ENAME, SUBSTR(SAL, 1, 1)
FROM EMP
ORDER BY 2 DESC;  -- 2는 SUBSTR(SAL, 1, 1) 즉 2열을 가리킨다.

SELECT DEPTNO, NAME,
       DECODE(DEPTNO, 101, DECODE(NAME, '조인형', 'BEST', 'GOOD'), 'N/A') "PRO"
FROM PROFESSOR;

--------------------------------------------------------

--1.
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE DEPTNO = 10;

--2.
SELECT ENAME, HIREDATE, DEPTNO
FROM EMP
WHERE EMPNO = 7369;

--3.
SELECT *
FROM EMP
WHERE ENAME = 'ALLEN';

--4 해결 안 됨
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';
FLUSH;
SELECT ENAME, DEPTNO, SAL
FROM EMP
WHERE HIREDATE = '1980/12/17';

--5
SELECT *
FROM EMP
WHERE JOB != 'MANAGER';

SELECT *
FROM EMP;

--6 해결 안 됨
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';

SELECT *
FROM EMP;
WHERE HIREDATE > '1981/04/02';

--7
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE SAL >= 800;

--8 
SELECT *
FROM EMP
WHERE DEPTNO >= 20;

--9 해결 안 됨
SELECT *
FROM EMP
WHERE HIREDATE < '1981/12/09';

--10 
SELECT EMPNO, ENAME
FROM EMP
WHERE EMPNO < 7698;

--11
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE HIREDATE > '1981/04/02' AND HIREDATE < '1982/12/09'; 

--12
SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL > 1600 AND SAL < 3000;

------------------------------------
5TH

SELECT COUNT(*)
FROM EMP;

SELECT MAX(SAL)
FROM EMP;

-- SUB QUERY: SELECT, FROM, WHERE 어디든지 가능.
SELECT *
FROM EMP
WHERE SAL = (SELECT COUNT(*) FROM EMP);

SELECT MAX(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DISTINCT JOB
FROM EMP;

SELECT MAX(SAL), JOB 
FROM EMP
GROUP BY JOB;

SELECT SUM(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO
ORDER BY 1 DESC;

SELECT COUNT(*), JOB
FROM EMP
GROUP BY JOB;

--------------------------------------------------

6TH

SELECT FLOOR(AVG(SAL)), JOB
FROM EMP
WHERE JOB != 'MANAGER'
GROUP BY JOB;

SELECT FLOOR(AVG(SAL)), JOB
FROM EMP
GROUP BY JOB;
HAVING JOB != 'MANAGER'

SELECT DEPTNO, AVG(NVL(SAL,0))
FROM EMP
--WHERE AVG(NVL(SAL,0)) > 2000;
GROUP BY DEPTNO
HAVING AVG(NVL(SAL,0)) > 2000; 

SELECT *
FROM GOGAK;

SELECT MAX(POINT)
FROM GOGAK;

-- 메모리 로딩 순서
SELECT MAX(POINT)  
FROM GOGAK
WHERE ROWNUM > 0 AND ROWNUM < 9;
UNION ALL
SELECT MAX(POINT)  
FROM (SELECT GNO, POINT, ROWNUM "NO" 
FROM GOGAK)
WHERE NO > 8 AND NO < 21;


SELECT GNO, GNAME, POINT, NO, DECODE(NO, 
FROM
(
SELECT GNO, GNAME, POINT, ROWNUM "NO"
FROM GOGAK
);

----------------------------------------------

7TH
SELECT *
FROM STUDENT;
-- NAME, JUMIN, JUMIN "GENDER" 1-'MAN, 2-'WOMAN'

SELECT NAME, JUMIN, DECODE(SUBSTR(JUMIN, 7, 1), 1, 'MAN', 2, 'WOMAN') "GENDER"
FROM STUDENT
WHERE DEPTNO1 = 101;

SELECT MAX(POINT)
FROM
(
    SELECT GNO, GNAME, POINT, NO,
    CASE WHEN NO < 9 THEN 1 ELSE 2 END "G"
    FROM
    (
        SELECT GNO, GNAME, POINT, ROWNUM "NO"
        FROM GOGAK
     )    
)
GROUP BY G;

SELECT MAX(POINT)  
FROM GOGAK
WHERE ROWNUM > 0 AND ROWNUM < 9;
UNION ALL
SELECT MAX(POINT)  
FROM (SELECT GNO, POINT, ROWNUM "NO" 
FROM GOGAK)
WHERE NO > 8 AND NO < 21;
