SELECT MAX(POINT), G
FROM
(
    SELECT MAX(POINT), CASE WHEN ROWNUM < 9 THEN 1 ELSE 2 END "G"
    FROM GOGAK
)
GROUP BY G;

SELECT WEEK, MAX(NUM_DAY)
FROM CAL
GROUP BY WEEK
ORDER BY WEEK;

--5명씩 끊어서 POINT의 합, 
SELECT SUM(POINT), CEIL(ROWNUM/5)
FROM GOGAK
GROUP BY CEIL(ROWNUM/5);

--같은 나이의 POINT의 합;
SELECT SUBSTR(JUMIN,1,2), SUM(POINT)
FROM GOGAK
GROUP BY SUBSTR(JUMIN,1,2);

--월급 순위 구하기
SELECT ENAME, SAL, ROWNUM "순위"
FROM
(SELECT ENAME, SAL
FROM EMP
ORDER BY SAL DESC
);

-- 11.
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';

SELECT ENAME, SAL, DEPTNO
FROM EMP 
WHERE HIREDATE > '1981/04/02' AND HIREDATE < '1982/12/09';

--12.
SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL > 1600 AND SAL < 3000;
SUBSTR(HIREDATE,3,2)!= 81
--15.
SELECT * 
FROM EMP
WHERE SUBSTR(HIREDATE,1,2) != '81';

---------------
SELECT ENAME, JOB, DEPTNO, TO_CHAR(S,'$99,999') 
FROM
(
SELECT ENAME, JOB, SAL+(DECODE(COMM, NULL, 0, COMM)) "S", DEPTNO
FROM EMP
ORDER BY DEPTNO
)
WHERE DEPTNO = 10

UNION ALL

SELECT NULL, NULL, NULL, TO_CHAR(SUM(SAL),'$99,999')
FROM EMP
WHERE DEPTNO = 10;

-------------------------

SELECT DEPTNO, JOB, AVG(SAL), COUNT(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO

SELECT DEPTNO, NULL JOB, ROUND(AVG(SAL),1) AVG_SAL, COUNT(*) CNT_EMP
FROM EMP
GROUP BY DEPTNO
UNION ALL
SELECT DEPTNO, JOB, ROUND(AVG(SAL),1) AVG_SAL, COUNT(*) CNT_EMP
FROM EMP
GROUP BY DEPTNO, JOB
UNION ALL
SELECT NULL DEPTNO, NULL JOB, ROUND(AVG(SAL),1) AVG_SAL, COUNT(*) CNT_EMP
FROM EMP
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, ROUND(AVG(SAL),1) AVG_SAL, COUNT(*) CNT_EMP
FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB);

--학생 테이블의 키(HEIGHT) 평균
SELECT AVG(HEIGHT)
FROM STUDENT;

--학생 테이블 학과별(DEPTNO1) 학생들 키 평균
SELECT ROUND(AVG(HEIGHT))
FROM STUDENT
GROUP BY DEPTNO1;

--학생 테이블 학과와 학년별 학생들의 키 평균, 소계값

SELECT DEPTNO1, GRADE, ROUND(AVG(HEIGHT)), COUNT(*)
FROM STUDENT
GROUP BY ROLLUP(DEPTNO1, GRADE);

--EMP 직업별 급여합계 조회 마지막줄에 총합계 추가해서 표시
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY ROLLUP(JOB);

--PANMAE 테이블에서 날짜별(P_DATE) 상품이(p_CODE) 몇 개(P_QTY)판매, 소계값
SELECT P_DATE, P_CODE, SUM(P_QTY)
FROM PANMAE
GROUP BY P_DATE, ROLLUP(P_CODE);

--PANMAE 테이블에서 상품별(P_CODE)로 날짜마다 (P_DATE) 얼마의 금액(P_TOTAL)이 판매, 소계값
SELECT P_CODE, P_DATE, SUM(P_TOTAL)
FROM PANMAE
GROUP BY ROLLUP(P_CODE, P_DATE);

-------------------------------
5교시

SELECT JOB, DEPTNO, SUM(SAL), COUNT(*)
FROM EMP
GROUP BY JOB, ROLLUP(DEPTNO)
ORDER BY DEPTNO;

SELECT POSITION, SUM(PAY)
FROM PROFESSOR
GROUP BY ROLLUP(POSITION);

SELECT GRADE, DEPTNO1, AVG(HEIGHT), COUNT(*)
FROM STUDENT
GROUP BY GRADE, ROLLUP(DEPTNO1);

-- 학년별 몸무게 평균, 전체 키 평균
SELECT GRADE, AVG(WEIGHT)
FROM STUDENT
GROUP BY ROLLUP(GRADE);

SELECT GRADE, AVG(WEIGHT)
FROM STUDENT
GROUP BY GRADE
UNION ALL
SELECT NULL, AVG(WEIGHT)
FROM NULL;

SELECT WEEK, 
DECODE(DAY), 
NUM_DAY
FROM CAL
WHERE WEEK = 1;

------------------------------

6교시

SELECT WEEK,
MAX(DECODE(DAY, '일', NUM_DAY)) "일",
MAX(DECODE(DAY, '월', NUM_DAY)) "월",
MAX(DECODE(DAY, '화', NUM_DAY)) "화",
MAX(DECODE(DAY, '수', NUM_DAY)) "수",
MAX(DECODE(DAY, '목', NUM_DAY)) "목",
MAX(DECODE(DAY, '금', NUM_DAY)) "금",
MAX(DECODE(DAY, '토', NUM_DAY)) "토"
FROM CAL
--WHERE WEEK = 1
GROUP BY WEEK
ORDER BY WEEK;

SELECT *
FROM CAL;

SELECT DEPTNO, 
COUNT(DECODE(JOB, 'CLERK', 0)) "CLERK",
COUNT(DECODE(JOB, 'MANAGER', 0)) "MANAGER",
COUNT(DECODE(JOB, 'PRESIDENT', 0)) "PRESIDENT",
COUNT(DECODE(JOB, 'ANALYST', 0)) "ANALYST",
COUNT(DECODE(JOB, 'SALESMAN', 0)) "SALESMAN"
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT DEPTNO, JOB, COUNT(*)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO;

SELECT AVG(PAY), POSITION
FROM PROFESSOR
GROUP BY POSITION;

SELECT POSITION, AVG(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT AVG(DECODE(POSITION, '정교수', PAY)) "정교수",
AVG(DECODE(POSITION, '조교수', PAY)) "조교수",
AVG(DECODE(POSITION, '전임강사', PAY)) "전임강사"
FROM PROFESSOR;

SELECT POSITION, DECODE(POSITION, '정교수', PAY)
FROM PROFESSOR;

SELECT GRADE, AVG(WEIGHT)
FROM STUDENT
GROUP BY GRADE;
 
--각 학년의 몸무게의 평균 PIVOT으로
SELECT 
AVG(DECODE(GRADE,1,WEIGHT)) "1", 
AVG(DECODE(GRADE,2,WEIGHT)) "2", 
AVG(DECODE(GRADE,3,WEIGHT)) "3", 
AVG(DECODE(GRADE,4,WEIGHT)) "4"
FROM STUDENT;
 
 
SELECT EMP_TYPE, AVG(PAY)
FROM EMP2
GROUP BY EMP_TYPE;

SELECT *
FROM STUDENT;

SELECT GRADE, AVG(WEIGHT)
FROM STUDENT;

-- 계약직, DEPTNO별, PAY의 합
SELECT EMP_TYPE, 
SUM(DECODE(DEPTNO, 1008, PAY)) "1008",
SUM(DECODE(DEPTNO, 1009, PAY)) "1009",
SUM(DECODE(DEPTNO, 1010, PAY)) "1010",
SUM(DECODE(DEPTNO, 1011, PAY)) "1011"
FROM EMP2
WHERE EMP_TYPE='계약직'
GROUP BY EMP_TYPE


SELECT EMP_TYPE, SUM(PAY)
FROM EMP2
GROUP BY EMP_TYPE;

SELECT EMP_TYPE,
DECODE(DEPTNO, 1008, PAY) "1008"
FROM EMP2
WHERE EMP_TYPE = '계약직';